version: "3.8"

services:
  nuxt-app:
    image: ${PROJECT_IMAGE_NAME}:${NUXT_ENV}-1.0
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - NUXT_ENV=${NUXT_ENV}
    container_name: ${PROJECT_IMAGE_NAME}
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NUXT_ENV=${NUXT_ENV}
    networks:
      - app_network

# laradock network
# networks:
  # app_network:
  #   name: laradock_backend
  #   external: true

networks:
  app_network:
    name: ${COMPOSE_PROJECT_NAME}_app_network
    driver: bridge
    external: true